title: Ela Conf
url: http://elaconf.com
baseurl: ''
location: "Philadelphia, Pennsylvania"
mission: "We are a not-for-profit event with a goal to create a safe, supportive, inspiring and comfortable <em>community</em> for women and marginalized genders to gain the confidence needed to become leaders, open source contributors, speakers, and teachers in the world of tech."
tagline: Empowering more women and marginalized genders to be leaders in tech.

author:
  name: Ela Conf
  email: hello@elaconf.com
  uri: http://elaconf.com

repository: elaconf/elaconf.github.io
modernizr: 2.8.3
jquery: 2.2.3
permalink: /:categories/:title/

sass:
  style: :compressed

twitter: elaconf
email: hello@elaconf.com
slack: https://docs.google.com/forms/d/e/1FAIpQLSctRXPSgQaXHkawUB2gP8NR0w41KsAbZit8AZr4q19swxQ50A/viewform

collections:
  organizers:
    output: true
    permalink: /organizers/:path/

exclude:
- Gemfile
- README.md
- package.json
- CNAME
- node_modules
- bin
- test

gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "organizers"
    values:
      layout: "speaker"
      category: "organizers"
      topic: Organizer
